core/urls.py
from django.urls import include, path, re_path
from .views import Home, upload, book_list, upload_book, delete_book, \
    BookListView, UploadBookView

app_name = 'core'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('upload/', upload, name='upload'),
    path('books/', book_list, name='book_list'),
    path('books/upload/', upload_book, name='upload_book'),
    path('books/<int:pk>/', delete_book, name='delete_book'),

    path('class/books/', BookListView.as_view(), name='class_book_list'),
    path('class/books/upload/', UploadBookView.as_view(), name='class_upload_book'),
]

website/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

from django.conf.urls.i18n import i18n_patterns
#{%- if cookiecutter.use_async == 'y' %}
#from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#{%- endif %}
#{%- if cookiecutter.use_drf == 'y' %}
#from rest_framework.authtoken.views import obtain_auth_token
#{%- endif %}

urlpatterns = [
    path('core/', include('core.urls')),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)
#{%- if cookiecutter.use_async == 'y' %}
#if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
#    urlpatterns += staticfiles_urlpatterns()
#{%- endif %}
#{% if cookiecutter.use_drf == 'y' %}
# API URLS
#urlpatterns += [
    # API base url
#    path("api/", include("config.api_router")),
    # DRF auth token
#    path("auth-token/", obtain_auth_token),
#]
#{%- endif %}
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] \
            + urlpatterns

core/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pdf = models.FileField(upload_to='books/pdfs/')
    cover = models.ImageField(upload_to='books/covers/', null=True, blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

core/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'pdf', 'cover')

core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy

from .forms import BookForm
from .models import Book


class Home(TemplateView):
    template_name = 'home.html'


def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)
    return render(request, 'upload.html', context)


def book_list(request):
    books = Book.objects.all()
    return render(request, 'book_list.html', {
        'books': books
    })


def upload_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('core:book_list')
    else:
        form = BookForm()
    return render(request, 'upload_book.html', {
        'form': form
    })


def delete_book(request, pk):
    if request.method == 'POST':
        book = Book.objects.get(pk=pk)
        book.delete()
    return redirect('core:book_list')


class BookListView(ListView):
    model = Book
    template_name = 'class_book_list.html'
    context_object_name = 'books'


class UploadBookView(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('core:class_book_list')
    template_name = 'upload_book.html'

base/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color:#decdc3">
    <div class="container">
      <a class="navbar-brand" href="{% url 'core:home' %}">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:upload' %}">Simple Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:book_list' %}">Model Forms Upload</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:class_book_list' %}">Model Forms Upload (CBV)</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

base/templates/book_list.html
{% extends 'base.html' %}

{% block content %}

  {% block content_header %}
    <h2>Books</h2>
    <p>
      <a href="{% url 'core:upload_book' %}" class="btn btn-primary">Upload book</a>
    </p>
  {% endblock %}

  <table class="table mb-0">
    <thead>
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
        <th>Download</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
        <tr>
          <td>
            {% if book.cover %}
              <img src="{{ book.cover.url }}" alt="{{ book.title }}" style="width:100px;">
            {% else %}
              <span class="text-muted">No cover</span>
            {% endif %}
          </td>
          <td>{{ book.title }}</td>
          <td>{{ book.author }}</td>
          <td>
            <a href="{{ book.pdf.url }}" class="btn btn-primary btn-sm" target="_blank">
              Download PDF
            </a>
          </td>
          <td>
            <form method="post" action="{% url 'core:delete_book' book.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

base/templates/class_book_list.html
{% extends 'book_list.html' %}

{% block content_header %}
  <h2>Books (Class-Based View)</h2>
  <p>
    <a href="{% url 'core:class_upload_book' %}" class="btn btn-primary">Upload book</a>
  </p>
{% endblock %}

base/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="card-title">Django File Upload Tutorial</h2>
  <p class="card-text">Example Django 2.1 / Python 3.7</p>
  <p class="card-text">
    Watch it on <a href="https://www.youtube.com/playlist?list=PLLxk3TkuAYnpm24Ma1XenNeq1oxxRcYFT">YouTube</a> or
    read the <a href="https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html">Blog Post</a>.
  </p>
  <p class="card-text">
    Vitor Freitas<br>
    <a href="https://twitter.com/vitorfs">@vitorfs</a>
  </p>
{% endblock %}

base/templates/upload.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="document">
    <button type="submit">Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
  {% endif %}
{% endblock %}

base/templates/upload_book.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h2>Upload book</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary">Upload book</button>
  </form>
{% endblock %}